/**
 * Watermarking Service - PII protection and download attribution
 */

export interface WatermarkOptions {
  partnerName: string;
  userName: string;
  timestamp: string;
  tenantId?: string;
  documentType?: 'audit_pack' | 'receipt' | 'report';
}

export class WatermarkingService {
  /**
   * Generate watermark text for documents
   * Format: "Generated by <partner>/<user>/<timestamp>"
   */
  static generateWatermark(options: WatermarkOptions): string {
    const { partnerName, userName, timestamp, documentType } = options;
    
    const baseWatermark = `Generated by ${partnerName}/${userName}/${timestamp}`;
    
    if (documentType) {
      return `${baseWatermark} - ${documentType.toUpperCase()}`;
    }
    
    return baseWatermark;
  }

  /**
   * Watermark content for audit packs and reports
   */
  static watermarkContent(content: string, watermark: string): string {
    const watermarkHeader = `\n=== DOCUMENT ATTRIBUTION ===\n${watermark}\n===========================\n\n`;
    const watermarkFooter = `\n\n=== END OF DOCUMENT ===\n${watermark}\n=======================`;
    
    return watermarkHeader + content + watermarkFooter;
  }

  /**
   * Create audit pack manifest with watermarking
   */
  static createAuditPackManifest(options: {
    packId: string;
    contents: string[];
    watermark: string;
    tenantId: string;
    dateRange: { startDate: string; endDate: string };
  }): string {
    const manifest = {
      packId: options.packId,
      generatedFor: options.tenantId,
      dateRange: options.dateRange,
      contents: options.contents,
      watermark: options.watermark,
      integrity: {
        generatedAt: new Date().toISOString(),
        version: '1.0',
        format: 'ZIP_WITH_MANIFEST',
      },
    };

    const manifestContent = JSON.stringify(manifest, null, 2);
    return this.watermarkContent(manifestContent, options.watermark);
  }

  /**
   * Protect PII in downloads - gate access and log
   */
  static async gatePIIAccess(options: {
    userId: string;
    partnerFirmId: string;
    tenantId: string;
    documentType: string;
    hasPII: boolean;
    requestDetails: any;
  }): Promise<{ allowed: boolean; reason?: string; watermark?: string }> {
    // Check if user has PII access permissions
    const hasPIIPermission = await this.checkPIIPermission(options.userId, options.partnerFirmId);
    
    if (options.hasPII && !hasPIIPermission) {
      return {
        allowed: false,
        reason: 'Insufficient permissions for PII access',
      };
    }

    // Log PII access attempt
    await this.logPIIAccess({
      userId: options.userId,
      partnerFirmId: options.partnerFirmId,
      tenantId: options.tenantId,
      documentType: options.documentType,
      granted: true,
      requestDetails: options.requestDetails,
    });

    // Generate watermark
    const watermark = this.generateWatermark({
      partnerName: `Partner-${options.partnerFirmId}`,
      userName: `User-${options.userId}`,
      timestamp: new Date().toISOString(),
      tenantId: options.tenantId,
      documentType: options.documentType as any,
    });

    return { allowed: true, watermark };
  }

  private static async checkPIIPermission(userId: string, partnerFirmId: string): Promise<boolean> {
    // Mock implementation - would check actual permissions
    return true; // For demo, allow PII access
  }

  private static async logPIIAccess(access: {
    userId: string;
    partnerFirmId: string;
    tenantId: string;
    documentType: string;
    granted: boolean;
    requestDetails: any;
  }): Promise<void> {
    console.log('PII ACCESS LOG:', {
      ...access,
      timestamp: new Date().toISOString(),
    });
  }
}